### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot drop air

### ISSUE THREAD

**Issue by trilliumhq** [zizmax/AcuteLoot#2]
java.lang.IllegalArgumentException: Cannot drop air
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.EntityItem.setItemStack(EntityItem.java:443) ~[patched_1.16.1.jar:git-Paper-127]
at org.bukkit.craftbukkit.v1_16_R1.entity.CraftItem.setItemStack(CraftItem.java:35) ~[patched_1.16.1.jar:git-Paper-127]
at acute.loot.Events.onPlayerFish(Events.java:238) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor168.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-127]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-127]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-127]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.EntityFishingHook.b(EntityFishingHook.java:442) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.ItemFishingRod.a(ItemFishingRod.java:18) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.ItemStack.a(ItemStack.java:379) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:412) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1526) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-127]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-127]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by zizmax** [comment]
Fixed in the lastest version!
